// The scenarios the example project is driven through. Each one starts from a
// fresh copy of examples/pulumi-basic and a fresh file backend. An edit names
// text of the example word for word, so when the example changes and a scenario
// no longer fits, the recorder stops instead of recording something else.
import type { Expectation, Scenario, Step } from "./recorder.ts";

// The command lines are the ones the adapter will use (Pulumi research,
// "Consequences for the design"). The recorder sets the working directory
// where the adapter may pass --cwd.
const QUIET = ["--non-interactive", "--color", "never"];

function init(cwd: string, stack: string): Step {
  return { kind: "setup", cwd, argv: ["pulumi", "stack", "init", stack, ...QUIET] };
}

function up(cwd: string, stack: string): Step {
  return {
    kind: "setup",
    cwd,
    argv: ["pulumi", "up", "--yes", "--skip-preview", ...QUIET, "--stack", stack],
  };
}

// The deploy as the adapter runs it (Pulumi research, "Non-interactive up").
// No --json: on `up` that streams engine events, which hold every property
// value. The stack outputs are kept out of what the tool prints, because an
// output can be a secret (record 0021).
function deploy(cwd: string, stack: string, expect: Expectation): Step {
  return {
    kind: "record",
    id: "up",
    cwd,
    argv: [
      "pulumi",
      "up",
      "--yes",
      "--skip-preview",
      "--suppress-outputs",
      ...QUIET,
      "--stack",
      stack,
    ],
    stdout: "text",
    expect,
  };
}

function preview(cwd: string, stack: string, expect: Expectation, id = "preview"): Step {
  return {
    kind: "record",
    id,
    cwd,
    argv: ["pulumi", "preview", "--json", ...QUIET, "--stack", stack],
    stdout: "json",
    expect,
  };
}

const NETWORK = "network/Pulumi.yaml";

function edit(find: string, replace: string, file = NETWORK): Step {
  return { kind: "edit", file, find, replace };
}

// Pieces of network/Pulumi.yaml, word for word.
const SUBNET = `  subnet:
    type: random:RandomString
    properties:
      length: 8
      special: false
    options:
      version: 4.21.2
`;
const SUBNET_RETAINED = SUBNET.replace(
  "    options:\n",
  "    options:\n      retainOnDelete: true\n",
);
const OUTPUTS = "outputs:\n";

const changedEnvironment = edit(
  "        NOTE: CANARY-VALUE\n",
  "        NOTE: CANARY-VALUE\n        STAGE: second\n",
);
const changedPrefix = edit("      prefix: net\n", "      prefix: lan\n");
const changedContent = edit(
  "      content: Managed by the network stack.\n    options:\n",
  "      content: Managed by the network stack, second edition.\n    options:\n      deleteBeforeReplace: true\n",
);
const removedSubnet = edit(SUBNET, "");
const addedResource = edit(
  OUTPUTS,
  `  extra:
    type: random:RandomPet
    properties:
      length: 3
    options:
      version: 4.21.2
${OUTPUTS}`,
);

// A deployed network:dev stack, then the given edits, then one preview.
function afterDeploy(
  name: string,
  description: string,
  edits: Step[],
  expect: Expectation,
): Scenario {
  return {
    name,
    description,
    steps: [
      init("network", "dev"),
      up("network", "dev"),
      ...edits,
      preview("network", "dev", expect),
    ],
  };
}

const MANY = 300;

function manyResources(): string {
  const resources = Array.from({ length: MANY }, (_, index) => {
    const name = `item${String(index + 1).padStart(3, "0")}`;
    return `  ${name}:\n    type: random:RandomId\n    properties:\n      byteLength: 4\n    options:\n      version: 4.21.2\n`;
  });
  return `name: many\nruntime: yaml\ndescription: Generated by the fixture recorder.\nresources:\n${resources.join("")}`;
}

export const SCENARIOS: Scenario[] = [
  {
    name: "version",
    description: "What the version check reads.",
    steps: [
      {
        kind: "record",
        id: "version",
        cwd: ".",
        argv: ["pulumi", "version"],
        stdout: "text",
        expect: { exit: "zero" },
      },
    ],
  },
  {
    name: "new-stack",
    description: "A stack that was never deployed. Every step is a create.",
    steps: [init("network", "dev"), preview("network", "dev", { exit: "zero", ops: ["create"] })],
  },
  {
    name: "new-stack-yml-project",
    description:
      "The same for app/, whose project file is spelled Pulumi.yml and which reads a file outside its directory.",
    steps: [init("app", "prod"), preview("app", "prod", { exit: "zero", ops: ["create"] })],
  },
  {
    name: "same-preview-twice",
    description:
      "The TypeScript program of site/, never deployed, previewed twice in a row. The order of the steps may differ between the two.",
    steps: [
      { kind: "setup", cwd: "site", argv: ["npm", "ci", "--no-audit", "--no-fund"] },
      init("site", "prod"),
      preview("site", "prod", { exit: "zero", ops: ["create"] }, "preview-1"),
      preview("site", "prod", { exit: "zero", ops: ["create"] }, "preview-2"),
    ],
  },
  afterDeploy("no-changes", "A deployed stack and no edit.", [], { exit: "zero" }),
  afterDeploy(
    "update",
    "One more environment variable on the command. An update in place.",
    [changedEnvironment],
    { exit: "zero", ops: ["update"] },
  ),
  afterDeploy(
    "replace",
    "A new prefix on the pet and new content in the file, the file with deleteBeforeReplace. Two replaces with replace reasons, one in each order.",
    [changedPrefix, changedContent],
    { exit: "zero", ops: ["replace"] },
  ),
  afterDeploy("delete", "The random string is gone from the program.", [removedSubnet], {
    exit: "zero",
    ops: ["delete"],
  }),
  afterDeploy(
    "mixed",
    "A create, an update, two replaces and a delete in one preview.",
    [changedEnvironment, changedPrefix, changedContent, removedSubnet, addedResource],
    { exit: "zero", ops: ["create", "update", "replace", "delete"] },
  ),
  afterDeploy(
    "outputs-only",
    "One more stack output and no resource change (record 0036).",
    [edit(OUTPUTS, `${OUTPUTS}  zone: \${zone}\n`)],
    { exit: "zero" },
  ),
  afterDeploy(
    "import",
    "A resource that the tool starts to track without creating it.",
    [
      edit(
        OUTPUTS,
        `  adopted:
    type: random:RandomId
    properties:
      byteLength: 4
    options:
      version: 4.21.2
      import: 3q2-7w
${OUTPUTS}`,
      ),
    ],
    { exit: "zero", ops: ["import"] },
  ),
  {
    name: "dropped-but-kept",
    description:
      "A resource deployed with retainOnDelete and then taken out of the program. The tool stops tracking it and the real object stays.",
    steps: [
      init("network", "dev"),
      edit(SUBNET, SUBNET_RETAINED),
      up("network", "dev"),
      edit(SUBNET_RETAINED, ""),
      preview("network", "dev", { exit: "zero", ops: ["delete"] }),
    ],
  },
  afterDeploy(
    "renamed-with-alias",
    "A resource under a new name, with an alias to the old one. The tool tracks it under a new address and the real object is left alone.",
    [
      edit("  name:\n    type: random:RandomPet\n", "  label:\n    type: random:RandomPet\n"),
      edit(
        "      prefix: net\n    options:\n",
        "      prefix: net\n    options:\n      aliases:\n        - name: name\n",
      ),
      edit(`\${name.id}`, `\${label.id}`),
    ],
    { exit: "zero" },
  ),
  afterDeploy(
    "changed-secret",
    "The secret config value has a new value. It shows as a changed property and its value is masked.",
    [
      {
        kind: "setup",
        cwd: "network",
        argv: [
          "pulumi",
          "config",
          "set",
          "--secret",
          "token",
          "CANARY-SECRET-ROTATED",
          ...QUIET,
          "--stack",
          "dev",
        ],
      },
    ],
    { exit: "zero", ops: ["update"] },
  ),
  {
    name: "deploy",
    description:
      "What apply runs for a stack that was never deployed: the fresh preview, then the deploy.",
    steps: [
      init("network", "dev"),
      preview("network", "dev", { exit: "zero", ops: ["create"] }),
      deploy("network", "dev", { exit: "zero" }),
    ],
  },
  {
    name: "deploy-failed",
    description:
      "The same with a command that fails when it is created. The preview is good, the deploy fails half way.",
    steps: [
      init("network", "dev"),
      edit("      create: echo network ready\n", "      create: exit 1\n"),
      preview("network", "dev", { exit: "zero", ops: ["create"] }),
      deploy("network", "dev", { exit: "nonzero" }),
    ],
  },
  {
    name: "program-error",
    description:
      "A resource type that does not exist. The preview fails and still prints a document.",
    steps: [
      init("network", "dev"),
      edit("    type: random:RandomString\n", "    type: random:NoSuchThing\n"),
      preview("network", "dev", { exit: "nonzero" }),
    ],
  },
  {
    name: "missing-stack",
    description: "A stack that the backend does not hold.",
    steps: [
      {
        kind: "record",
        id: "preview",
        cwd: "network",
        argv: ["pulumi", "preview", "--json", ...QUIET, "--stack", "ghost"],
        stdout: "text",
        expect: { exit: "nonzero" },
      },
    ],
  },
  {
    name: "missing-config",
    description: "A config value the program requires is not in the stack file.",
    steps: [
      init("network", "dev"),
      edit("  network:zone: dev-a\n", "", "network/Pulumi.dev.yaml"),
      {
        kind: "record",
        id: "preview",
        cwd: "network",
        argv: ["pulumi", "preview", "--json", ...QUIET, "--stack", "dev"],
        stdout: "text",
        expect: { exit: "nonzero" },
      },
    ],
  },
  {
    name: "many-resources",
    description: `A generated program of ${MANY} resources, never deployed.`,
    steps: [
      { kind: "write", file: "generated/many/Pulumi.yaml", content: manyResources() },
      init("generated/many", "big"),
      preview("generated/many", "big", { exit: "zero", ops: ["create"] }),
    ],
  },
];
