apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-settings
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Values.version | quote }}
data:
  greeting: {{ printf "CANARY-VALUE %s" (required "greeting is required" .Values.greeting) | quote }}
  app.properties: |
    color={{ .Values.color }}
